const mongoose = require('mongoose');

const ngoProfileSchema = new mongoose.Schema({
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, unique: true },
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', index: true },
  organizationName: { type: String, required: true, trim: true, maxlength: 160 },
  name: { type: String, trim: true, maxlength: 160 },
  description: { type: String, trim: true, maxlength: 2000 },
  category: { type: String, trim: true, maxlength: 80, index: true },
  address: { type: String, trim: true, maxlength: 240 },
  city: { type: String, trim: true, maxlength: 80, index: true },
  state: { type: String, trim: true, maxlength: 80, index: true },
  latitude: { type: Number, min: -90, max: 90 },
  longitude: { type: Number, min: -180, max: 180 },
  location: { lat: Number, lng: Number },
  phone: { type: String, trim: true, maxlength: 40 },
  email: { type: String, trim: true, lowercase: true, maxlength: 160 },
  website: { type: String, trim: true, maxlength: 500 },
  officialDonationUrl: { type: String, trim: true, maxlength: 500 },
  logo: { type: String, trim: true, maxlength: 500 },
  images: [{ type: String, trim: true, maxlength: 500 }],
  acceptedDonationTypes: [{ type: String, trim: true, maxlength: 40 }],
  notAcceptedDonationTypes: [{ type: String, trim: true, maxlength: 40 }],
  urgentlyNeededItems: [{ type: String, trim: true, maxlength: 120 }],
  requirements: [{ type: String, trim: true, maxlength: 300 }],
  donationInformation: { type: String, trim: true, maxlength: 2000 },
  pickupAvailable: { type: Boolean, default: false },
  dropOffAvailable: { type: Boolean, default: false },
  pickupAreas: [{ type: String, trim: true, maxlength: 100 }],
  operatingHours: { type: mongoose.Schema.Types.Mixed, default: {} },
  documents: [{ url: String, kind: String, originalName: String }],
  verificationStatus: { type: String, enum: ['pending', 'verified', 'rejected', 'flagged'], default: 'pending', index: true },
  registrationInformation: { type: String, trim: true, maxlength: 2000 },
  verificationInformation: { type: String, trim: true, maxlength: 2000 },
  officialWebsite: { type: String, trim: true, maxlength: 500 },
  contact: { type: String, trim: true, maxlength: 200 },
  registrationNumber: { type: String, trim: true, maxlength: 120 },
  sourceUrl: { type: String, trim: true, maxlength: 500 },
  verificationSource: { type: String, trim: true, maxlength: 300 },
  lastVerifiedAt: { type: Date },
  reviewedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  reviewedAt: { type: Date },
  reviewNotes: { type: String, trim: true, maxlength: 2000 },
  isPublished: { type: Boolean, default: false }
}, { timestamps: true, versionKey: false });

module.exports = mongoose.model('NGOProfile', ngoProfileSchema);
